# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_view_photo_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewPhotoWidget(object):
    def setupUi(self, ViewPhotoWidget):
        ViewPhotoWidget.setObjectName("ViewPhotoWidget")
        ViewPhotoWidget.resize(1040, 624)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ViewPhotoWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(ViewPhotoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 600))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.face_list = QtWidgets.QListWidget(self.frame)
        self.face_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.face_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.face_list.setIconSize(QtCore.QSize(50, 50))
        self.face_list.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.face_list.setFlow(QtWidgets.QListView.TopToBottom)
        self.face_list.setGridSize(QtCore.QSize(0, 100))
        self.face_list.setViewMode(QtWidgets.QListView.ListMode)
        self.face_list.setBatchSize(99)
        self.face_list.setObjectName("face_list")
        self.gridLayout_2.addWidget(self.face_list, 0, 0, 1, 1)
        self.face_list_remove_btn = QtWidgets.QPushButton(self.frame)
        self.face_list_remove_btn.setObjectName("face_list_remove_btn")
        self.gridLayout_2.addWidget(self.face_list_remove_btn, 1, 0, 1, 1)
        self.face_list_update_btn = QtWidgets.QPushButton(self.frame)
        self.face_list_update_btn.setObjectName("face_list_update_btn")
        self.gridLayout_2.addWidget(self.face_list_update_btn, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(ViewPhotoWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(800, 600))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.picture_lb = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_lb.sizePolicy().hasHeightForWidth())
        self.picture_lb.setSizePolicy(sizePolicy)
        self.picture_lb.setMinimumSize(QtCore.QSize(748, 492))
        self.picture_lb.setText("")
        self.picture_lb.setScaledContents(False)
        self.picture_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.picture_lb.setObjectName("picture_lb")
        self.gridLayout.addWidget(self.picture_lb, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previous_btn = QtWidgets.QPushButton(self.frame_4)
        self.previous_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.previous_btn.setObjectName("previous_btn")
        self.horizontalLayout_2.addWidget(self.previous_btn)
        self.face_btn = QtWidgets.QPushButton(self.frame_4)
        self.face_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.face_btn.setObjectName("face_btn")
        self.horizontalLayout_2.addWidget(self.face_btn)
        self.next_btn = QtWidgets.QPushButton(self.frame_4)
        self.next_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_2.addWidget(self.next_btn)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(ViewPhotoWidget)
        QtCore.QMetaObject.connectSlotsByName(ViewPhotoWidget)

    def retranslateUi(self, ViewPhotoWidget):
        _translate = QtCore.QCoreApplication.translate
        ViewPhotoWidget.setWindowTitle(_translate("ViewPhotoWidget", "View Photo"))
        self.face_list_remove_btn.setText(_translate("ViewPhotoWidget", "Remove"))
        self.face_list_update_btn.setText(_translate("ViewPhotoWidget", "Update"))
        self.previous_btn.setText(_translate("ViewPhotoWidget", "Previous"))
        self.face_btn.setText(_translate("ViewPhotoWidget", "Faces"))
        self.next_btn.setText(_translate("ViewPhotoWidget", "Next"))

